-- E-commerce multi-tenant da barbearia: pedidos, cupons, estoque reservado e carrinhos recuperaveis.

alter table public.barbearia_produtos
  add column if not exists estoque_reservado numeric(12,3) not null default 0 check (estoque_reservado >= 0);

create table public.barbearia_cupons (
  id uuid primary key default gen_random_uuid(),
  barbearia_id uuid not null references public.barbearias(id) on delete cascade,
  codigo text not null,
  descricao text,
  tipo text not null check (tipo in ('percentual', 'fixo')),
  valor numeric(12,2) not null check (valor > 0),
  pedido_minimo numeric(12,2) not null default 0 check (pedido_minimo >= 0),
  desconto_maximo numeric(12,2) check (desconto_maximo is null or desconto_maximo > 0),
  limite_usos integer check (limite_usos is null or limite_usos > 0),
  usos integer not null default 0 check (usos >= 0),
  inicia_em timestamptz,
  termina_em timestamptz,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (barbearia_id, id)
);

create unique index barbearia_cupons_codigo_idx
  on public.barbearia_cupons (barbearia_id, lower(codigo));
create index barbearia_cupons_validade_idx
  on public.barbearia_cupons (barbearia_id, ativo, termina_em);

create table public.barbearia_pedidos (
  id uuid primary key default gen_random_uuid(),
  barbearia_id uuid not null references public.barbearias(id) on delete cascade,
  numero bigint generated by default as identity,
  token_publico uuid not null default gen_random_uuid() unique,
  cliente_id uuid,
  cupom_id uuid,
  status text not null default 'aguardando_pagamento' check (status in (
    'aguardando_pagamento', 'confirmado', 'em_separacao', 'pronto_retirada',
    'enviado', 'concluido', 'cancelado', 'estornado'
  )),
  pagamento_status text not null default 'pendente' check (pagamento_status in (
    'pendente', 'pago', 'falhou', 'cancelado', 'estornado', 'pagar_na_retirada'
  )),
  entrega_tipo text not null default 'retirada' check (entrega_tipo in ('retirada', 'entrega')),
  nome_cliente text not null,
  telefone_cliente text not null,
  email_cliente text,
  cpf_cliente text,
  cep text,
  endereco text,
  numero_endereco text,
  complemento text,
  bairro text,
  cidade text,
  estado text,
  referencia_entrega text,
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  desconto numeric(12,2) not null default 0 check (desconto >= 0),
  frete numeric(12,2) not null default 0 check (frete >= 0),
  total numeric(12,2) not null default 0 check (total >= 0),
  cupom_codigo text,
  forma_pagamento text not null default 'UNDEFINED',
  asaas_payment_id text unique,
  invoice_url text,
  pago_em timestamptz,
  expiracao_reserva_em timestamptz,
  observacoes text,
  payload_pagamento jsonb not null default '{}'::jsonb,
  origem jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (barbearia_id, id),
  unique (barbearia_id, numero),
  foreign key (barbearia_id, cliente_id)
    references public.barbearia_clientes(barbearia_id, id) on delete restrict,
  foreign key (barbearia_id, cupom_id)
    references public.barbearia_cupons(barbearia_id, id) on delete restrict
);

create index barbearia_pedidos_status_idx
  on public.barbearia_pedidos (barbearia_id, status, created_at desc);
create index barbearia_pedidos_pagamento_idx
  on public.barbearia_pedidos (barbearia_id, pagamento_status, created_at desc);
create index barbearia_pedidos_cliente_idx
  on public.barbearia_pedidos (barbearia_id, cliente_id, created_at desc);
create index barbearia_pedidos_reserva_idx
  on public.barbearia_pedidos (status, expiracao_reserva_em)
  where status = 'aguardando_pagamento';

create table public.barbearia_pedido_itens (
  id uuid primary key default gen_random_uuid(),
  barbearia_id uuid not null references public.barbearias(id) on delete cascade,
  pedido_id uuid not null,
  produto_id uuid not null,
  nome_produto text not null,
  sku text,
  imagem_url text,
  quantidade numeric(12,3) not null check (quantidade > 0),
  valor_unitario numeric(12,2) not null check (valor_unitario >= 0),
  desconto numeric(12,2) not null default 0 check (desconto >= 0),
  total numeric(12,2) not null check (total >= 0),
  created_at timestamptz not null default now(),
  foreign key (barbearia_id, pedido_id)
    references public.barbearia_pedidos(barbearia_id, id) on delete cascade,
  foreign key (barbearia_id, produto_id)
    references public.barbearia_produtos(barbearia_id, id) on delete restrict
);

create index barbearia_pedido_itens_pedido_idx
  on public.barbearia_pedido_itens (barbearia_id, pedido_id);
create index barbearia_pedido_itens_produto_idx
  on public.barbearia_pedido_itens (barbearia_id, produto_id, created_at desc);

create table public.barbearia_estoque_reservas (
  id uuid primary key default gen_random_uuid(),
  barbearia_id uuid not null references public.barbearias(id) on delete cascade,
  pedido_id uuid not null,
  produto_id uuid not null,
  quantidade numeric(12,3) not null check (quantidade > 0),
  status text not null default 'ativa' check (status in ('ativa', 'convertida', 'liberada', 'expirada')),
  expira_em timestamptz not null,
  finalizada_em timestamptz,
  created_at timestamptz not null default now(),
  foreign key (barbearia_id, pedido_id)
    references public.barbearia_pedidos(barbearia_id, id) on delete cascade,
  foreign key (barbearia_id, produto_id)
    references public.barbearia_produtos(barbearia_id, id) on delete restrict,
  unique (pedido_id, produto_id)
);

create index barbearia_estoque_reservas_ativas_idx
  on public.barbearia_estoque_reservas (barbearia_id, expira_em)
  where status = 'ativa';

create table public.barbearia_estoque_movimentos (
  id uuid primary key default gen_random_uuid(),
  barbearia_id uuid not null references public.barbearias(id) on delete cascade,
  produto_id uuid not null,
  pedido_id uuid,
  tipo text not null check (tipo in ('reserva', 'liberacao', 'venda', 'estorno', 'ajuste', 'entrada', 'saida')),
  quantidade numeric(12,3) not null,
  estoque_anterior numeric(12,3) not null,
  estoque_posterior numeric(12,3) not null,
  observacoes text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  foreign key (barbearia_id, produto_id)
    references public.barbearia_produtos(barbearia_id, id) on delete restrict,
  foreign key (barbearia_id, pedido_id)
    references public.barbearia_pedidos(barbearia_id, id) on delete restrict
);

create index barbearia_estoque_movimentos_produto_idx
  on public.barbearia_estoque_movimentos (barbearia_id, produto_id, created_at desc);

create table public.barbearia_carrinhos_abandonados (
  id uuid primary key default gen_random_uuid(),
  barbearia_id uuid not null references public.barbearias(id) on delete cascade,
  sessao_token uuid not null,
  token_recuperacao uuid not null default gen_random_uuid() unique,
  pedido_id uuid,
  status text not null default 'ativo' check (status in ('ativo', 'convertido', 'recuperado', 'expirado', 'descartado')),
  nome text,
  telefone text,
  email text,
  consentimento_recuperacao boolean not null default false,
  consentimento_em timestamptz,
  itens jsonb not null default '[]'::jsonb,
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  cupom_codigo text,
  origem jsonb not null default '{}'::jsonb,
  ultima_interacao_em timestamptz not null default now(),
  lembrete_enviado_em timestamptz,
  quantidade_lembretes integer not null default 0 check (quantidade_lembretes >= 0),
  convertido_em timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (barbearia_id, id),
  unique (barbearia_id, sessao_token),
  foreign key (barbearia_id, pedido_id)
    references public.barbearia_pedidos(barbearia_id, id) on delete restrict
);

create index barbearia_carrinhos_recuperacao_idx
  on public.barbearia_carrinhos_abandonados (barbearia_id, status, ultima_interacao_em desc);
create index barbearia_carrinhos_lembrete_idx
  on public.barbearia_carrinhos_abandonados (status, consentimento_recuperacao, ultima_interacao_em)
  where status = 'ativo' and consentimento_recuperacao = true;

alter table public.barbearia_pagamentos
  add column if not exists pedido_id uuid;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'barbearia_pagamentos_pedido_fk'
  ) then
    alter table public.barbearia_pagamentos
      add constraint barbearia_pagamentos_pedido_fk
      foreign key (barbearia_id, pedido_id)
      references public.barbearia_pedidos(barbearia_id, id) on delete restrict;
  end if;
end;
$$;

create index if not exists barbearia_pagamentos_pedido_idx
  on public.barbearia_pagamentos (barbearia_id, pedido_id);

create or replace function public.criar_pedido_loja(
  p_barbearia_id uuid,
  p_cliente_id uuid,
  p_itens jsonb,
  p_nome text,
  p_telefone text,
  p_email text default null,
  p_cpf text default null,
  p_entrega_tipo text default 'retirada',
  p_frete numeric default 0,
  p_cep text default null,
  p_endereco text default null,
  p_numero_endereco text default null,
  p_complemento text default null,
  p_bairro text default null,
  p_cidade text default null,
  p_estado text default null,
  p_referencia_entrega text default null,
  p_cupom_codigo text default null,
  p_forma_pagamento text default 'UNDEFINED',
  p_reserva_minutos integer default 30,
  p_origem jsonb default '{}'::jsonb
)
returns table (pedido_id uuid, token_publico uuid, numero bigint, subtotal numeric, desconto numeric, frete numeric, total numeric)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pedido public.barbearia_pedidos%rowtype;
  v_produto public.barbearia_produtos%rowtype;
  v_cupom public.barbearia_cupons%rowtype;
  v_item record;
  v_subtotal numeric(12,2) := 0;
  v_desconto numeric(12,2) := 0;
  v_frete numeric(12,2) := greatest(coalesce(p_frete, 0), 0);
  v_total numeric(12,2) := 0;
  v_expira_em timestamptz := now() + make_interval(mins => greatest(10, least(coalesce(p_reserva_minutos, 30), 240)));
  v_item_count integer := 0;
begin
  if p_entrega_tipo not in ('retirada', 'entrega') then
    raise exception 'Forma de entrega invalida.';
  end if;

  if coalesce(trim(p_nome), '') = '' or coalesce(trim(p_telefone), '') = '' then
    raise exception 'Nome e telefone sao obrigatorios.';
  end if;

  if jsonb_typeof(p_itens) <> 'array' or jsonb_array_length(p_itens) = 0 then
    raise exception 'O carrinho esta vazio.';
  end if;

  for v_item in
    select produto_id, sum(quantidade)::numeric(12,3) as quantidade
    from jsonb_to_recordset(p_itens) as item(produto_id uuid, quantidade numeric)
    group by produto_id
  loop
    v_item_count := v_item_count + 1;
    if v_item.quantidade <= 0 or v_item.quantidade <> trunc(v_item.quantidade) then
      raise exception 'Quantidade invalida no carrinho.';
    end if;

    select * into v_produto
    from public.barbearia_produtos
    where id = v_item.produto_id
      and barbearia_id = p_barbearia_id
      and ativo = true
      and publicado_site = true
    for update;

    if not found then
      raise exception 'Produto indisponivel.';
    end if;

    if (v_produto.estoque_atual - v_produto.estoque_reservado) < v_item.quantidade then
      raise exception 'Estoque insuficiente para %.', v_produto.nome;
    end if;

    v_subtotal := v_subtotal + round(v_produto.preco * v_item.quantidade, 2);
  end loop;

  if v_item_count = 0 then
    raise exception 'O carrinho esta vazio.';
  end if;

  if coalesce(trim(p_cupom_codigo), '') <> '' then
    select * into v_cupom
    from public.barbearia_cupons
    where barbearia_id = p_barbearia_id
      and lower(codigo) = lower(trim(p_cupom_codigo))
      and ativo = true
      and (inicia_em is null or inicia_em <= now())
      and (termina_em is null or termina_em >= now())
    for update;

    if not found then
      raise exception 'Cupom invalido ou expirado.';
    end if;
    if v_subtotal < v_cupom.pedido_minimo then
      raise exception 'Este cupom exige um pedido minimo de R$ %.', v_cupom.pedido_minimo;
    end if;
    if v_cupom.limite_usos is not null and v_cupom.usos >= v_cupom.limite_usos then
      raise exception 'O limite de uso deste cupom foi atingido.';
    end if;

    if v_cupom.tipo = 'percentual' then
      v_desconto := round(v_subtotal * (v_cupom.valor / 100), 2);
      if v_cupom.desconto_maximo is not null then
        v_desconto := least(v_desconto, v_cupom.desconto_maximo);
      end if;
    else
      v_desconto := least(v_cupom.valor, v_subtotal);
    end if;
  end if;

  v_total := greatest(round(v_subtotal - v_desconto + v_frete, 2), 0);

  insert into public.barbearia_pedidos (
    barbearia_id, cliente_id, cupom_id, nome_cliente, telefone_cliente, email_cliente, cpf_cliente,
    entrega_tipo, cep, endereco, numero_endereco, complemento, bairro, cidade, estado, referencia_entrega,
    subtotal, desconto, frete, total, cupom_codigo, forma_pagamento, expiracao_reserva_em, origem
  ) values (
    p_barbearia_id, p_cliente_id, v_cupom.id, trim(p_nome), trim(p_telefone), nullif(trim(p_email), ''), nullif(trim(p_cpf), ''),
    p_entrega_tipo, nullif(trim(p_cep), ''), nullif(trim(p_endereco), ''), nullif(trim(p_numero_endereco), ''),
    nullif(trim(p_complemento), ''), nullif(trim(p_bairro), ''), nullif(trim(p_cidade), ''), nullif(trim(p_estado), ''),
    nullif(trim(p_referencia_entrega), ''), v_subtotal, v_desconto, v_frete, v_total, v_cupom.codigo,
    coalesce(nullif(trim(p_forma_pagamento), ''), 'UNDEFINED'), v_expira_em, coalesce(p_origem, '{}'::jsonb)
  ) returning * into v_pedido;

  for v_item in
    select produto_id, sum(quantidade)::numeric(12,3) as quantidade
    from jsonb_to_recordset(p_itens) as item(produto_id uuid, quantidade numeric)
    group by produto_id
  loop
    select * into v_produto
    from public.barbearia_produtos
    where id = v_item.produto_id and barbearia_id = p_barbearia_id;

    update public.barbearia_produtos
    set estoque_reservado = estoque_reservado + v_item.quantidade
    where id = v_produto.id and barbearia_id = p_barbearia_id;

    insert into public.barbearia_pedido_itens (
      barbearia_id, pedido_id, produto_id, nome_produto, sku, imagem_url,
      quantidade, valor_unitario, total
    ) values (
      p_barbearia_id, v_pedido.id, v_produto.id, v_produto.nome, v_produto.sku, v_produto.imagem_url,
      v_item.quantidade, v_produto.preco, round(v_produto.preco * v_item.quantidade, 2)
    );

    insert into public.barbearia_estoque_reservas (
      barbearia_id, pedido_id, produto_id, quantidade, expira_em
    ) values (
      p_barbearia_id, v_pedido.id, v_produto.id, v_item.quantidade, v_expira_em
    );

    insert into public.barbearia_estoque_movimentos (
      barbearia_id, produto_id, pedido_id, tipo, quantidade,
      estoque_anterior, estoque_posterior, observacoes
    ) values (
      p_barbearia_id, v_produto.id, v_pedido.id, 'reserva', 0,
      v_produto.estoque_atual, v_produto.estoque_atual, 'Reserva temporaria do pedido online.'
    );
  end loop;

  if v_cupom.id is not null then
    update public.barbearia_cupons set usos = usos + 1 where id = v_cupom.id;
  end if;

  return query select v_pedido.id, v_pedido.token_publico, v_pedido.numero,
    v_subtotal, v_desconto, v_frete, v_total;
end;
$$;

create or replace function public.cancelar_pedido_loja(p_pedido_id uuid, p_motivo text default null)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pedido public.barbearia_pedidos%rowtype;
  v_reserva public.barbearia_estoque_reservas%rowtype;
  v_estoque numeric(12,3);
begin
  select * into v_pedido from public.barbearia_pedidos where id = p_pedido_id for update;
  if not found then return false; end if;
  if v_pedido.status in ('cancelado', 'estornado') then return true; end if;
  if v_pedido.pagamento_status = 'pago' then
    raise exception 'Pedido pago deve ser estornado, nao cancelado.';
  end if;

  for v_reserva in
    select * from public.barbearia_estoque_reservas
    where pedido_id = p_pedido_id and status = 'ativa'
    for update
  loop
    select estoque_atual into v_estoque
    from public.barbearia_produtos
    where id = v_reserva.produto_id and barbearia_id = v_reserva.barbearia_id
    for update;

    update public.barbearia_produtos
    set estoque_reservado = greatest(estoque_reservado - v_reserva.quantidade, 0)
    where id = v_reserva.produto_id and barbearia_id = v_reserva.barbearia_id;

    update public.barbearia_estoque_reservas
    set status = case when expira_em <= now() then 'expirada' else 'liberada' end,
        finalizada_em = now()
    where id = v_reserva.id;

    insert into public.barbearia_estoque_movimentos (
      barbearia_id, produto_id, pedido_id, tipo, quantidade,
      estoque_anterior, estoque_posterior, observacoes
    ) values (
      v_reserva.barbearia_id, v_reserva.produto_id, p_pedido_id, 'liberacao', 0,
      v_estoque, v_estoque, coalesce(p_motivo, 'Reserva liberada.')
    );
  end loop;

  if v_pedido.cupom_id is not null then
    update public.barbearia_cupons set usos = greatest(usos - 1, 0) where id = v_pedido.cupom_id;
  end if;

  update public.barbearia_pedidos
  set status = 'cancelado', pagamento_status = 'cancelado',
      observacoes = concat_ws(E'\n', observacoes, p_motivo)
  where id = p_pedido_id;
  return true;
end;
$$;

create or replace function public.confirmar_pagamento_pedido_loja(
  p_pedido_id uuid,
  p_asaas_payment_id text default null,
  p_payload jsonb default '{}'::jsonb,
  p_pago_em timestamptz default now()
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pedido public.barbearia_pedidos%rowtype;
  v_reserva public.barbearia_estoque_reservas%rowtype;
  v_produto public.barbearia_produtos%rowtype;
begin
  select * into v_pedido from public.barbearia_pedidos where id = p_pedido_id for update;
  if not found then return false; end if;
  if v_pedido.pagamento_status = 'pago' then return true; end if;
  if v_pedido.status in ('cancelado', 'estornado') then
    raise exception 'Pedido cancelado nao pode ser confirmado.';
  end if;

  for v_reserva in
    select * from public.barbearia_estoque_reservas
    where pedido_id = p_pedido_id and status = 'ativa'
    for update
  loop
    select * into v_produto
    from public.barbearia_produtos
    where id = v_reserva.produto_id and barbearia_id = v_reserva.barbearia_id
    for update;

    if v_produto.estoque_atual < v_reserva.quantidade then
      raise exception 'Estoque inconsistente para confirmar o pedido.';
    end if;

    update public.barbearia_produtos
    set estoque_atual = estoque_atual - v_reserva.quantidade,
        estoque_reservado = greatest(estoque_reservado - v_reserva.quantidade, 0)
    where id = v_produto.id and barbearia_id = v_produto.barbearia_id;

    update public.barbearia_estoque_reservas
    set status = 'convertida', finalizada_em = now()
    where id = v_reserva.id;

    insert into public.barbearia_estoque_movimentos (
      barbearia_id, produto_id, pedido_id, tipo, quantidade,
      estoque_anterior, estoque_posterior, observacoes
    ) values (
      v_produto.barbearia_id, v_produto.id, p_pedido_id, 'venda', -v_reserva.quantidade,
      v_produto.estoque_atual, v_produto.estoque_atual - v_reserva.quantidade,
      'Venda confirmada pelo pagamento do pedido online.'
    );
  end loop;

  update public.barbearia_pedidos
  set status = 'em_separacao', pagamento_status = 'pago', pago_em = coalesce(p_pago_em, now()),
      asaas_payment_id = coalesce(p_asaas_payment_id, asaas_payment_id),
      payload_pagamento = coalesce(p_payload, '{}'::jsonb)
  where id = p_pedido_id;
  return true;
end;
$$;

create or replace function public.estornar_pedido_loja(p_pedido_id uuid, p_motivo text default null)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pedido public.barbearia_pedidos%rowtype;
  v_item public.barbearia_pedido_itens%rowtype;
  v_estoque numeric(12,3);
begin
  select * into v_pedido from public.barbearia_pedidos where id = p_pedido_id for update;
  if not found then return false; end if;
  if v_pedido.status = 'estornado' then return true; end if;
  if v_pedido.pagamento_status <> 'pago' then
    raise exception 'Somente pedidos pagos podem ser estornados.';
  end if;

  for v_item in select * from public.barbearia_pedido_itens where pedido_id = p_pedido_id
  loop
    select estoque_atual into v_estoque
    from public.barbearia_produtos
    where id = v_item.produto_id and barbearia_id = v_item.barbearia_id
    for update;

    update public.barbearia_produtos
    set estoque_atual = estoque_atual + v_item.quantidade
    where id = v_item.produto_id and barbearia_id = v_item.barbearia_id;

    insert into public.barbearia_estoque_movimentos (
      barbearia_id, produto_id, pedido_id, tipo, quantidade,
      estoque_anterior, estoque_posterior, observacoes
    ) values (
      v_item.barbearia_id, v_item.produto_id, p_pedido_id, 'estorno', v_item.quantidade,
      v_estoque, v_estoque + v_item.quantidade, coalesce(p_motivo, 'Estorno do pedido online.')
    );
  end loop;

  if v_pedido.cupom_id is not null then
    update public.barbearia_cupons set usos = greatest(usos - 1, 0) where id = v_pedido.cupom_id;
  end if;

  update public.barbearia_pedidos
  set status = 'estornado', pagamento_status = 'estornado',
      observacoes = concat_ws(E'\n', observacoes, p_motivo)
  where id = p_pedido_id;
  return true;
end;
$$;

create or replace function public.expirar_pedidos_loja()
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_pedido record;
  v_total integer := 0;
begin
  for v_pedido in
    select id from public.barbearia_pedidos
    where status = 'aguardando_pagamento'
      and pagamento_status = 'pendente'
      and expiracao_reserva_em < now()
    for update skip locked
  loop
    perform public.cancelar_pedido_loja(v_pedido.id, 'Reserva expirada automaticamente.');
    v_total := v_total + 1;
  end loop;
  return v_total;
end;
$$;

revoke all on function public.criar_pedido_loja(uuid, uuid, jsonb, text, text, text, text, text, numeric, text, text, text, text, text, text, text, text, text, text, integer, jsonb) from public, anon, authenticated;
revoke all on function public.cancelar_pedido_loja(uuid, text) from public, anon, authenticated;
revoke all on function public.confirmar_pagamento_pedido_loja(uuid, text, jsonb, timestamptz) from public, anon, authenticated;
revoke all on function public.estornar_pedido_loja(uuid, text) from public, anon, authenticated;
revoke all on function public.expirar_pedidos_loja() from public, anon, authenticated;

grant execute on function public.criar_pedido_loja(uuid, uuid, jsonb, text, text, text, text, text, numeric, text, text, text, text, text, text, text, text, text, text, integer, jsonb) to service_role;
grant execute on function public.cancelar_pedido_loja(uuid, text) to service_role;
grant execute on function public.confirmar_pagamento_pedido_loja(uuid, text, jsonb, timestamptz) to service_role;
grant execute on function public.estornar_pedido_loja(uuid, text) to service_role;
grant execute on function public.expirar_pedidos_loja() to service_role;

do $$
declare table_name text;
begin
  foreach table_name in array array[
    'barbearia_cupons', 'barbearia_pedidos', 'barbearia_pedido_itens',
    'barbearia_estoque_reservas', 'barbearia_estoque_movimentos', 'barbearia_carrinhos_abandonados'
  ] loop
    execute format('alter table public.%I enable row level security', table_name);
  end loop;

  foreach table_name in array array['barbearia_cupons', 'barbearia_pedidos', 'barbearia_carrinhos_abandonados']
  loop
    execute format(
      'create trigger %I before update on public.%I for each row execute function app_private.set_barbearia_updated_at()',
      'set_updated_at_' || table_name, table_name
    );
  end loop;
end;
$$;

create policy barbearia_cupons_crud_membros on public.barbearia_cupons
  for all to authenticated
  using (app_private.usuario_tem_acesso_barbearia(barbearia_id))
  with check (app_private.usuario_tem_acesso_barbearia(barbearia_id));
create policy barbearia_pedidos_crud_membros on public.barbearia_pedidos
  for all to authenticated
  using (app_private.usuario_tem_acesso_barbearia(barbearia_id))
  with check (app_private.usuario_tem_acesso_barbearia(barbearia_id));
create policy barbearia_pedido_itens_crud_membros on public.barbearia_pedido_itens
  for all to authenticated
  using (app_private.usuario_tem_acesso_barbearia(barbearia_id))
  with check (app_private.usuario_tem_acesso_barbearia(barbearia_id));
create policy barbearia_estoque_reservas_crud_membros on public.barbearia_estoque_reservas
  for all to authenticated
  using (app_private.usuario_tem_acesso_barbearia(barbearia_id))
  with check (app_private.usuario_tem_acesso_barbearia(barbearia_id));
create policy barbearia_estoque_movimentos_crud_membros on public.barbearia_estoque_movimentos
  for all to authenticated
  using (app_private.usuario_tem_acesso_barbearia(barbearia_id))
  with check (app_private.usuario_tem_acesso_barbearia(barbearia_id));
create policy barbearia_carrinhos_select_membros on public.barbearia_carrinhos_abandonados
  for select to authenticated
  using (app_private.usuario_tem_acesso_barbearia(barbearia_id));
create policy barbearia_carrinhos_update_membros on public.barbearia_carrinhos_abandonados
  for update to authenticated
  using (app_private.usuario_tem_acesso_barbearia(barbearia_id))
  with check (app_private.usuario_tem_acesso_barbearia(barbearia_id));

grant select, insert, update, delete on public.barbearia_cupons, public.barbearia_pedidos,
  public.barbearia_pedido_itens, public.barbearia_estoque_reservas, public.barbearia_estoque_movimentos
  to authenticated;
grant select, update on public.barbearia_carrinhos_abandonados to authenticated;
grant all privileges on public.barbearia_cupons, public.barbearia_pedidos, public.barbearia_pedido_itens,
  public.barbearia_estoque_reservas, public.barbearia_estoque_movimentos, public.barbearia_carrinhos_abandonados
  to service_role;
grant usage, select on sequence public.barbearia_pedidos_numero_seq to authenticated, service_role;

comment on table public.barbearia_pedidos is 'Pedidos de produtos originados na lojinha publica da barbearia.';
comment on table public.barbearia_carrinhos_abandonados is 'Carrinhos persistidos para metricas e recuperacao com consentimento.';
comment on column public.barbearia_produtos.estoque_reservado is 'Quantidade temporariamente reservada por pedidos ainda nao pagos.';
